package:
  name: adaptive-lighting
  version: "1.30.1"
  epoch: 1
  description: "Home Assistant custom integration for adaptive lighting"
  copyright:
    - license: Apache-2.0
  target-architecture:
    - x86_64
    - aarch64
  scriptlets:
    post-install: |
      #!/bin/sh
      chown -R homeassistant:homeassistant /var/lib/homeassistant/custom_components/adaptive_lighting 2>/dev/null || true

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/basnijholt/adaptive-lighting.git
      tag: v${{package.version}}
      expected-commit: e0f812d406ffa8ec9309ef2d1bfd27529c67c4ec

  - runs: |
      install -dm755 "${{targets.destdir}}/var/lib/homeassistant/custom_components"
      cp -r custom_components/adaptive_lighting \
        "${{targets.destdir}}/var/lib/homeassistant/custom_components/"

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      packages:
        - busybox
        - python3
  pipeline:
    - runs: |
        # Test that the custom component files exist
        test -d /var/lib/homeassistant/custom_components/adaptive_lighting
        test -f /var/lib/homeassistant/custom_components/adaptive_lighting/__init__.py
        test -f /var/lib/homeassistant/custom_components/adaptive_lighting/manifest.json
    - runs: |
        # Verify manifest.json is valid JSON and contains expected fields
        python3 -c "
        import json
        with open('/var/lib/homeassistant/custom_components/adaptive_lighting/manifest.json') as f:
            m = json.load(f)
            assert m['domain'] == 'adaptive_lighting', 'Wrong domain'
            assert 'version' in m, 'Missing version'
            print(f\"Adaptive Lighting v{m['version']} installed successfully\")
        "
