package:
  name: codex
  version: "0.97.0"
  epoch: 0
  description: "OpenAI Codex CLI - coding agent for the terminal"
  copyright:
    - license: Apache-2.0
  target-architecture:
    - x86_64
    - aarch64
  checks:
    disabled:
      - usrmerge

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/openai/codex/releases/download/rust-v${{package.version}}/codex-${{build.arch}}-unknown-linux-musl.tar.gz
      extract: false

  - runs: |
      # Verify checksum
      case "${{build.arch}}" in
        x86_64)
          EXPECTED_SHA256="0d6184f8d9f8da235217bedeb699d47ad914bcd8169ac0b701c248e2b14bbb3f"
          ;;
        aarch64)
          EXPECTED_SHA256="acfbd0b3bacd18558faba9c41f074038a70c680006098fc58c0326eace3f3cc8"
          ;;
      esac
      echo "${EXPECTED_SHA256}  codex-${{build.arch}}-unknown-linux-musl.tar.gz" | sha256sum -c -

      # Extract and install
      tar -xzf "codex-${{build.arch}}-unknown-linux-musl.tar.gz"
      install -Dm755 "codex-${{build.arch}}-unknown-linux-musl" "${{targets.destdir}}/usr/bin/codex"

  - runs: |
      mkdir -p "${{targets.destdir}}/usr/share/licenses/codex"
      printf '%s\n' \
        'Copyright 2025 OpenAI' \
        'Licensed under the Apache License, Version 2.0' \
        'https://github.com/openai/codex/blob/main/LICENSE' \
        > "${{targets.destdir}}/usr/share/licenses/codex/LICENSE"

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/edge/main
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
  pipeline:
    - runs: |
        # Test that binary exists and is executable
        test -x /usr/bin/codex
    - runs: |
        # Test that codex --version works
        codex --version
    - runs: |
        # Test that codex --help works
        codex --help
