package:
  name: detect-radio-module
  version: 0_git20250116
  epoch: 0
  description: "HomeMatic RF module detection tool"
  copyright:
    - license: Apache-2.0
  target-architecture:
    - aarch64
    - x86_64
  checks:
    disabled:
      - usrmerge

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - ca-certificates
      - build-base
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/alexreinert/piVCCU.git
      branch: master
      expected-commit: 8be20bf4b777bdf4cd47b25f5903c2deeeb5ae4a

  - runs: |
      cd detect_radio_module
      # Fix musl compatibility: 'uint' is a glibc-specific typedef
      make CXXFLAGS="-pthread -static-libstdc++ -Duint=unsigned"
      install -Dm755 detect_radio_module "${{targets.destdir}}"/usr/bin/detect_radio_module

  - uses: strip

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
  pipeline:
    - runs: |
        # Test that binary exists and runs (will show usage or error without hardware)
        detect_radio_module || true
