package:
  name: gcompat-custom
  version: 0_git20250117
  epoch: 0
  description: "gcompat with full fortify function support for OCCU binaries"
  copyright:
    - license: LGPL-2.1-only
  dependencies:
    runtime: []
    provides:
      - gcompat
      - libc6-compat
    replaces:
      - gcompat
  target-architecture:
    - aarch64
    - x86_64
  checks:
    disabled:
      - usrmerge

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - build-base
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/elohmeier/gcompat.git
      branch: current
      expected-commit: f5f4486c9ff90814cc7c7cec5030b47621d135b7
      destination: gcompat-src

  - runs: |
      cd gcompat-src

      # Determine architecture-specific linker path
      ARCH="$(uname -m)"
      case "$ARCH" in
        aarch64)
          LINKER_PATH="/lib/ld-musl-aarch64.so.1"
          ;;
        x86_64)
          LINKER_PATH="/lib/ld-musl-x86_64.so.1"
          ;;
        *)
          echo "Unsupported architecture: $ARCH"
          exit 1
          ;;
      esac

      # Build gcompat
      make \
        LINKER_PATH="$LINKER_PATH" \
        CFLAGS="-O2 -fPIC" \
        WITH_OBSTACK=no

      # Install to destdir
      make install DESTDIR="${{targets.destdir}}"

      # Create symlinks for common glibc ld-linux names
      mkdir -p "${{targets.destdir}}/lib64"
      case "$ARCH" in
        aarch64)
          ln -sf /lib/ld-linux.so.2 "${{targets.destdir}}/lib/ld-linux-aarch64.so.1"
          ln -sf /lib/ld-linux.so.2 "${{targets.destdir}}/lib64/ld-linux-aarch64.so.1"
          ;;
        x86_64)
          ln -sf /lib/ld-linux.so.2 "${{targets.destdir}}/lib/ld-linux-x86-64.so.2"
          ln -sf /lib/ld-linux.so.2 "${{targets.destdir}}/lib64/ld-linux-x86-64.so.2"
          ;;
      esac

  - uses: strip

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
  pipeline:
    - runs: |
        # Test that library exists
        test -f /lib/libgcompat.so.0
        test -f /lib/ld-linux.so.2

        # Check that library exports fortify symbols
        nm -D /lib/libgcompat.so.0 | grep -q "__fdelt_chk"
        nm -D /lib/libgcompat.so.0 | grep -q "__snprintf_chk"
        nm -D /lib/libgcompat.so.0 | grep -q "__printf_chk"
        nm -D /lib/libgcompat.so.0 | grep -q "__syslog_chk"

        echo "gcompat-custom tests passed"
