package:
  name: home-assistant
  version: 2026.1.2
  epoch: 1
  description: "Home Assistant Core - Open-source home automation platform"
  copyright:
    - license: Apache-2.0
  options:
    # Disable auto-detection which adds Wolfi-style dependencies
    no-depends: true
  dependencies:
    runtime:
      - python314
      - libjpeg-turbo
      - libturbojpeg
      - ffmpeg
      - ffmpeg-libs
      - eudev
      - eudev-libs
      - libsodium
      - libffi
      - sqlite-libs
      - libcap2
      - openssl
      - ca-certificates
      - tzdata
  target-architecture:
    - x86_64
    - aarch64
  checks:
    disabled:
      - usrmerge
  scriptlets:
    pre-install: |
      #!/bin/sh
      addgroup -S homeassistant 2>/dev/null || true
      adduser -S -D -H -h /var/lib/homeassistant -s /sbin/nologin -G homeassistant \
        -g "Home Assistant" homeassistant 2>/dev/null || true
      # Add to groups for hardware access
      adduser homeassistant dialout 2>/dev/null || true
      adduser homeassistant plugdev 2>/dev/null || true
      adduser homeassistant gpio 2>/dev/null || true
    post-install: |
      #!/bin/sh
      echo ""
      echo "=== Home Assistant Core installed ==="
      echo ""
      echo "Quick start:"
      echo "  rc-service home-assistant start"
      echo "  rc-update add home-assistant default"
      echo ""
      echo "Config files:"
      echo "  /etc/conf.d/home-assistant    Service options"
      echo "  /var/lib/homeassistant        Configuration directory"
      echo ""
      echo "Web interface:"
      echo "  http://HOST:8123"
      echo ""
      echo "Bundled integrations:"
      echo "  MQTT, ZHA (Zigbee), Z-Wave JS, ESPHome, HomeKit"
      echo ""

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - ca-certificates
      - build-base
      - python314
      - uv
      - libjpeg-turbo-dev
      - libturbojpeg
      - ffmpeg-dev
      - eudev-dev
      - libsodium-dev
      - libffi-dev
      - sqlite-dev
      - libcap-dev
      - zlib-dev
      - openssl-dev
      - rust
      - cargo
      - linux-headers
  environment:
    PIP_CACHE_DIR: /var/cache/melange/pip
    CARGO_HOME: /var/cache/melange/cargo
    UV_CACHE_DIR: /var/cache/melange/uv

pipeline:
  # Step 1: Create requirements.in with all desired packages
  - runs: |
      cat > requirements.in << 'EOF'
      # Home Assistant Core
      homeassistant==${{package.version}}

      # Frontend (required for web UI)
      home-assistant-frontend

      # USB device detection
      pyudev
      aiousbwatcher

      # Network discovery
      async-upnp-client
      aiodhcpwatcher

      # Core dependencies that need to be pre-built (have C extensions)
      ha-ffmpeg

      # Audio/media metadata
      mutagen

      # Voice assistant (conversation)
      hassil
      home-assistant-intents

      # Integrations: MQTT
      paho-mqtt

      # Integrations: Zigbee (ZHA)
      zha

      # Integrations: Z-Wave
      zwave-js-server-python
      pyserial

      # Integrations: ESPHome
      aioesphomeapi
      esphome-dashboard-api

      # Integrations: HomeKit
      HAP-python
      aiohomekit

      # Media/streaming
      go2rtc-client
      PyTurboJPEG
      EOF

  # Step 2: Use uv to compile a complete lockfile with all dependencies resolved
  - runs: |
      uv pip compile requirements.in \
        --python-platform linux \
        --python-version 3.14 \
        --prerelease=allow \
        --no-annotate \
        --output-file requirements.lock

      echo "=== Generated lockfile with $(wc -l < requirements.lock) packages ==="

  # Step 3: Create a venv and install all packages
  - runs: |
      # Remove PEP 668 marker to allow venv's ensurepip to work
      rm -f /usr/lib/python3.14/EXTERNALLY-MANAGED

      # Create venv in the target location
      python3.14 -m venv "${{targets.destdir}}/opt/home-assistant"

      # Activate and install using uv (much faster than pip)
      . "${{targets.destdir}}/opt/home-assistant/bin/activate"

      uv pip install \
        --no-cache \
        --compile-bytecode \
        -r requirements.lock

      # Fix permissions on venv lock file
      chmod 644 "${{targets.destdir}}/opt/home-assistant/.lock" || true

      deactivate

  # Step 4: Create wrapper script that uses the venv
  - runs: |
      install -dm755 "${{targets.destdir}}"/usr/bin

      cat > "${{targets.destdir}}"/usr/bin/hass << 'EOF'
      #!/bin/sh
      exec /opt/home-assistant/bin/python3 -m homeassistant "$@"
      EOF
      chmod 755 "${{targets.destdir}}"/usr/bin/hass

  # Step 5: Install OpenRC scripts and supporting files
  - runs: |
      install -Dm755 home-assistant/home-assistant.initd "${{targets.destdir}}"/etc/init.d/home-assistant
      install -Dm644 home-assistant/home-assistant.confd "${{targets.destdir}}"/etc/conf.d/home-assistant
      install -Dm644 home-assistant/99-home-assistant.rules "${{targets.destdir}}"/etc/udev/rules.d/99-home-assistant.rules

      # Create data directory
      install -dm755 "${{targets.destdir}}"/var/lib/homeassistant

  # Step 6: Save the lockfile for reproducibility and future updates
  - runs: |
      install -Dm644 requirements.lock "${{targets.destdir}}"/opt/home-assistant/requirements.lock
      install -Dm644 requirements.in "${{targets.destdir}}"/opt/home-assistant/requirements.in

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/edge/main
        - https://dl-cdn.alpinelinux.org/alpine/edge/community
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      packages:
        - busybox
  pipeline:
    - runs: |
        # Test that homeassistant module can be imported
        /opt/home-assistant/bin/python3 -c "from homeassistant.const import __version__; print(f'Home Assistant {__version__}')"
    - runs: |
        # Test that hass entry point works
        hass --version
    - runs: |
        # Test frontend import
        /opt/home-assistant/bin/python3 -c "import hass_frontend; print('Frontend OK')"
    - runs: |
        # Test help output
        hass --help
