package:
  name: matter-server
  version: 8.1.2
  epoch: 13
  description: "Open Home Foundation Matter Server - WebSocket-based Matter controller"
  copyright:
    - license: Apache-2.0
  options:
    # Disable auto-detection which adds Wolfi-style python-3.12-base
    no-depends: true
  dependencies:
    runtime:
      - chip-sdk
      - python3
      - py3-aiohttp
      - py3-coloredlogs
      - py3-orjson
      - py3-cryptography
      - py3-zeroconf
      - py3-atomicwrites
      - py3-yaml
      - py3-construct
      - py3-dacite
      - py3-rich
      - py3-ecdsa
  target-architecture:
    - x86_64
    - aarch64
  checks:
    disabled:
      - usrmerge
  scriptlets:
    pre-install: |
      #!/bin/sh
      addgroup -S matter 2>/dev/null || true
      adduser -S -D -H -h /var/lib/matter-server -s /sbin/nologin -G matter \
        -g "Matter Server" matter 2>/dev/null || true
      # Add to bluetooth group for BLE commissioning (if group exists)
      adduser matter bluetooth 2>/dev/null || true
    post-install: |
      #!/bin/sh
      echo ""
      echo "=== Matter Server installed ==="
      echo ""
      echo "Quick start:"
      echo "  rc-service matter-server start"
      echo "  rc-update add matter-server default"
      echo ""
      echo "Config files:"
      echo "  /etc/conf.d/matter-server    Service options"
      echo ""
      echo "Ports:"
      echo "  5580  WebSocket API (Home Assistant, other clients)"
      echo ""
      echo "Data:"
      echo "  /var/lib/matter-server       Persistent storage"
      echo ""
      echo "Logs:"
      echo "  /var/log/matter-server.log"
      echo ""
      echo "Integration:"
      echo "  Home Assistant: Add Matter integration, connect to ws://HOST:5580/ws"
      echo ""

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - ca-certificates
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - chip-sdk
      # System packages for dependencies (not bundled)
      - py3-aiohttp
      - py3-coloredlogs
      - py3-orjson
      - py3-cryptography
      - py3-zeroconf
      - py3-atomicwrites
      - py3-yaml
      - py3-construct
      - py3-dacite
      - py3-rich
      - py3-ecdsa
  environment:
    PIP_CACHE_DIR: /var/cache/melange/pip

pipeline:
  # Install python-matter-server and dependencies
  - runs: |
      pyver=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
      sitepkgs="${{targets.destdir}}/usr/lib/python$pyver/site-packages"
      mkdir -p "$sitepkgs"

      # Download python-matter-server and aiorun (not in Alpine)
      python3 -m pip wheel \
        --wheel-dir .dist \
        "python-matter-server==${{package.version}}" \
        "aiorun>=2024.5.1"

      # Install wheels, skipping packages provided by Alpine or chip-sdk
      for whl in .dist/*.whl; do
        case "$(basename "$whl")" in
          # Skip CHIP packages (provided by chip-sdk)
          home_assistant_chip*)
            echo "Skipping $whl (provided by chip-sdk)"
            continue
            ;;
          # Skip packages provided by Alpine
          aiohttp-*|coloredlogs-*|orjson-*|cryptography-*|zeroconf-*|atomicwrites-*|PyYAML-*|construct-*|dacite-*|rich-*|ecdsa-*)
            echo "Skipping $whl (provided by Alpine)"
            continue
            ;;
          # Skip transitive dependencies also provided by Alpine
          aiosignal-*|attrs-*|yarl-*|multidict-*|frozenlist-*|charset_normalizer-*|cffi-*|pycparser-*|idna-*|aiohappyeyeballs-*|propcache-*|humanfriendly-*|ifaddr-*|markdown_it_py-*|mdurl-*|pygments-*|typing_extensions-*|async_timeout-*|six-*)
            echo "Skipping $whl (provided by Alpine)"
            continue
            ;;
        esac
        python3 -m pip install \
          --no-deps \
          --no-compile \
          --target "$sitepkgs" \
          "$whl"
      done

      # Byte-compile Python files
      python3 -m compileall -q "$sitepkgs" || true

      # Create bin directory and install entry point
      install -dm755 "${{targets.destdir}}"/usr/bin

      printf '%s\n' '#!/usr/bin/python3' 'import sys' 'from matter_server.server.__main__ import main' 'sys.exit(main())' > "${{targets.destdir}}"/usr/bin/matter-server
      chmod 755 "${{targets.destdir}}"/usr/bin/matter-server

      # Install CLI tool for commissioning
      install -Dm755 matter-server/matter-commission "${{targets.destdir}}"/usr/bin/matter-commission

      # Install OpenRC init script (from package source dir)
      install -Dm755 matter-server/matter-server.initd "${{targets.destdir}}"/etc/init.d/matter-server
      install -Dm644 matter-server/matter-server.confd "${{targets.destdir}}"/etc/conf.d/matter-server

      # Create data directory
      install -dm755 "${{targets.destdir}}"/var/lib/matter-server

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/edge/main
        - https://dl-cdn.alpinelinux.org/alpine/edge/community
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
  pipeline:
    - runs: |
        # Test that chip module can be imported
        python3 -c "from chip.exceptions import ChipStackError; print('chip module OK')"
    - runs: |
        # Test that matter_server module can be imported
        python3 -c "from matter_server.server.__main__ import main; print('matter_server module OK')"
    - runs: |
        # Test help output
        matter-server --help
