package:
  name: matter-server
  version: 8.1.2
  epoch: 9
  description: "Open Home Foundation Matter Server - WebSocket-based Matter controller"
  copyright:
    - license: Apache-2.0
  options:
    # Disable auto-detection which adds Wolfi-style python-3.12-base
    no-depends: true
  dependencies:
    runtime:
      - chip-sdk
      - python3
  target-architecture:
    - x86_64
    - aarch64
  checks:
    disabled:
      - usrmerge
  scriptlets:
    pre-install: |
      #!/bin/sh
      addgroup -S matter 2>/dev/null || true
      adduser -S -D -H -h /var/lib/matter-server -s /sbin/nologin -G matter \
        -g "Matter Server" matter 2>/dev/null || true
      # Add to bluetooth group for BLE commissioning (if group exists)
      adduser matter bluetooth 2>/dev/null || true
    post-install: |
      #!/bin/sh
      echo ""
      echo "=== Matter Server installed ==="
      echo ""
      echo "Quick start:"
      echo "  rc-service matter-server start"
      echo "  rc-update add matter-server default"
      echo ""
      echo "Config files:"
      echo "  /etc/conf.d/matter-server    Service options"
      echo ""
      echo "Ports:"
      echo "  5580  WebSocket API (Home Assistant, other clients)"
      echo ""
      echo "Data:"
      echo "  /var/lib/matter-server       Persistent storage"
      echo ""
      echo "Logs:"
      echo "  /var/log/matter-server.log"
      echo ""
      echo "Integration:"
      echo "  Home Assistant: Add Matter integration, connect to ws://HOST:5580/ws"
      echo ""

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - ca-certificates
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - chip-sdk
  environment:
    PIP_CACHE_DIR: /var/cache/melange/pip

pipeline:
  # Install python-matter-server and dependencies
  - runs: |
      pyver=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
      sitepkgs="${{targets.destdir}}/usr/lib/python$pyver/site-packages"
      mkdir -p "$sitepkgs"

      # Download and install python-matter-server and dependencies
      python3 -m pip wheel \
        --wheel-dir .dist \
        "python-matter-server==${{package.version}}" \
        "aiohttp>=3.9.0" \
        "aiorun>=2024.5.1" \
        "coloredlogs>=15.0" \
        "orjson>=3.9.0" \
        "cryptography>=42.0.0" \
        "zeroconf>=0.131.0" \
        "atomicwrites>=1.4.0" \
        "pyyaml>=6.0" \
        "construct>=2.10" \
        "dacite>=1.8" \
        "rich>=13.0" \
        "ecdsa>=0.18"

      # Install all wheels (skip CHIP packages - provided by chip-sdk)
      for whl in .dist/*.whl; do
        case "$whl" in
          *home_assistant_chip*) echo "Skipping $whl (provided by chip-sdk)"; continue ;;
        esac
        python3 -m pip install \
          --no-deps \
          --no-compile \
          --target "$sitepkgs" \
          "$whl"
      done

      # Byte-compile Python files
      python3 -m compileall -q "$sitepkgs" || true

      # Create bin directory and install entry point
      install -dm755 "${{targets.destdir}}"/usr/bin

      printf '%s\n' '#!/usr/bin/python3' 'import sys' 'from matter_server.server.__main__ import main' 'sys.exit(main())' > "${{targets.destdir}}"/usr/bin/matter-server
      chmod 755 "${{targets.destdir}}"/usr/bin/matter-server

      # Install OpenRC init script (from package source dir)
      install -Dm755 matter-server/matter-server.initd "${{targets.destdir}}"/etc/init.d/matter-server
      install -Dm644 matter-server/matter-server.confd "${{targets.destdir}}"/etc/conf.d/matter-server

      # Create data directory
      install -dm755 "${{targets.destdir}}"/var/lib/matter-server

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/edge/main
        - https://dl-cdn.alpinelinux.org/alpine/edge/community
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
  pipeline:
    - runs: |
        # Test that chip module can be imported
        python3 -c "from chip.exceptions import ChipStackError; print('chip module OK')"
    - runs: |
        # Test that matter_server module can be imported
        python3 -c "from matter_server.server.__main__ import main; print('matter_server module OK')"
    - runs: |
        # Test help output
        matter-server --help
