package:
  name: matter-server
  version: 8.1.2
  epoch: 1
  description: "Open Home Foundation Matter Server - WebSocket-based Matter controller"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - libuv
      - zlib
      - json-c
      - libnl3
      - glib
      - dbus-libs
      - libssl3
      - libcrypto3
  target-architecture:
    - x86_64
    - aarch64
  checks:
    disabled:
      - usrmerge
  scriptlets:
    pre-install: |
      addgroup -S matter 2>/dev/null || true
      adduser -S -D -H -h /var/lib/matter-server -s /sbin/nologin -G matter \
        -g "Matter Server" matter 2>/dev/null || true
      # Add to bluetooth group for BLE commissioning (if group exists)
      adduser matter bluetooth 2>/dev/null || true

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - ca-certificates
      - build-base
      - git
      - gn
      - ninja
      - python3
      - python3-dev
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - py3-virtualenv
      - patch
      - openssl-dev
      - glib-dev
      - libnl3-dev
      - dbus-dev
      - readline-dev
      - libffi-dev
      - yaml-dev
      - unzip
      - zstd
      - wget
      # gcompat needed for zap-cli (Node.js app) during code generation
      - gcompat
  environment:
    PIP_CACHE_DIR: /var/cache/melange/pip
    # Skip CIPD in Pigweed - use system tools instead
    PW_ENVSETUP_NO_CIPD: "1"

pipeline:
  # Clone connectedhomeip and checkout submodules
  - runs: |
      # CHIP SDK version matching the python-matter-server release
      _chip_version="2025.7.0"

      # Clone chip-wheels at the matching tag to get correct connectedhomeip commit
      git clone --depth 1 --branch "$_chip_version" \
        https://github.com/home-assistant-libs/chip-wheels.git chip-wheels

      cd chip-wheels

      # Initialize connectedhomeip submodule
      git submodule update --init --depth 1 connectedhomeip

      cd connectedhomeip

      # Checkout required submodules for linux platform
      python3 scripts/checkout_submodules.py --shallow --platform linux

  # Apply patches from chip-wheels
  - runs: |
      cd chip-wheels/connectedhomeip
      for patch in ../*.patch; do
        echo "Applying $patch"
        patch -p1 < "$patch"
      done

  # Set up Python build environment
  - runs: |
      cd chip-wheels/connectedhomeip

      # Install Python build requirements
      python3 -m pip install --break-system-packages \
        click coloredlogs jinja2 lark python-path lxml \
        pip-tools virtualenv wheel build mypy mypy-protobuf protobuf \
        cffi cryptography ecdsa

  # Download zap-cli for code generation (glibc binary, needs gcompat)
  - runs: |
      # Get zap version from chip-wheels
      _zap_version=$(cat chip-wheels/connectedhomeip/scripts/setup/zap.version)

      # Determine platform
      case "${{build.arch}}" in
        x86_64) _zap_platform="linux-x64" ;;
        aarch64) _zap_platform="linux-arm64" ;;
      esac

      # Download and install zap-cli
      mkdir -p /usr/local/bin
      wget -q "https://github.com/project-chip/zap/releases/download/${_zap_version}/zap-${_zap_platform}.zip" -O /tmp/zap.zip
      unzip -q /tmp/zap.zip -d /tmp/zap
      mv /tmp/zap/zap-cli /usr/local/bin/
      chmod +x /usr/local/bin/zap-cli
      rm -rf /tmp/zap /tmp/zap.zip

  # Create minimal Pigweed environment (skip CIPD bootstrap)
  - runs: |
      cd chip-wheels/connectedhomeip

      # Initialize pigweed submodule if needed
      git submodule update --init third_party/pigweed/repo

      # Create empty pigweed_environment.gni (required by build system)
      # This is what the configure script does to avoid full Pigweed bootstrap
      echo "# Auto-generated by melange build" > build_overrides/pigweed_environment.gni

      # Set PW_PROJECT_ROOT for pip requirements that reference it
      export PW_PROJECT_ROOT="$(pwd)"

      # Install Pigweed Python packages
      python3 -m pip install --break-system-packages \
        -r scripts/setup/requirements.build.txt

  # Build Python wheels
  - runs: |
      cd chip-wheels/connectedhomeip

      # Set up environment
      export PW_PROJECT_ROOT="$(pwd)"
      export PW_ROOT="$(pwd)/third_party/pigweed/repo"

      # Determine CPU tag
      case "${{build.arch}}" in
        x86_64) _cpu="x86_64" ;;
        aarch64) _cpu="aarch64" ;;
      esac

      # Generate build files with GN
      # Use custom toolchain with native compilers (no cross-compile prefix)
      gn gen out/python --args="
        custom_toolchain=\"//build/toolchain/custom\"
        target_cc=\"gcc\"
        target_cxx=\"g++\"
        target_ar=\"ar\"
        chip_crypto=\"boringssl\"
        enable_rtti=true
        chip_config_memory_debug_checks=false
        chip_config_memory_debug_dmalloc=false
        chip_mdns=\"minimal\"
        chip_minmdns_default_policy=\"libnl\"
        chip_python_version=\"${{package.version}}\"
        chip_python_package_prefix=\"home-assistant-chip\"
        chip_python_platform_tag=\"musllinux_1_2\"
        chip_project_config_include_dirs=[\"//config/python\"]
      "

      # Build Python wheels
      ninja -C out/python python_wheels

  # Install all components
  - runs: |
      pyver=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
      sitepkgs="${{targets.destdir}}/usr/lib/python$pyver/site-packages"
      mkdir -p "$sitepkgs"

      # Install CHIP wheels built from source
      for whl in chip-wheels/connectedhomeip/out/python/controller/python/*.whl; do
        echo "Installing $whl"
        python3 -m pip install \
          --no-deps \
          --no-compile \
          --target "$sitepkgs" \
          "$whl"
      done

      # Download and install python-matter-server and dependencies
      python3 -m pip wheel \
        --wheel-dir .dist \
        "python-matter-server==${{package.version}}" \
        "aiohttp>=3.9.0" \
        "aiorun>=2024.5.1" \
        "coloredlogs>=15.0" \
        "orjson>=3.9.0" \
        "cryptography>=42.0.0" \
        "zeroconf>=0.131.0" \
        "atomicwrites>=1.4.0" \
        "pyyaml>=6.0" \
        "construct>=2.10" \
        "dacite>=1.8" \
        "rich>=13.0"

      # Install all wheels (except CHIP ones which are already installed)
      for whl in .dist/*.whl; do
        case "$whl" in
          *home_assistant_chip*) continue ;;
        esac
        python3 -m pip install \
          --no-deps \
          --no-compile \
          --target "$sitepkgs" \
          "$whl"
      done

      # Byte-compile Python files
      python3 -m compileall -q "$sitepkgs" || true

      # Create bin directory and install entry point
      install -dm755 "${{targets.destdir}}"/usr/bin

      printf '%s\n' '#!/usr/bin/python3' 'import sys' 'from matter_server.server.__main__ import main' 'sys.exit(main())' > "${{targets.destdir}}"/usr/bin/matter-server
      chmod 755 "${{targets.destdir}}"/usr/bin/matter-server

      # Install OpenRC init script (from package source dir)
      install -Dm755 matter-server/matter-server.initd "${{targets.destdir}}"/etc/init.d/matter-server
      install -Dm644 matter-server/matter-server.confd "${{targets.destdir}}"/etc/conf.d/matter-server

      # Create data directory
      install -dm755 "${{targets.destdir}}"/var/lib/matter-server
