package:
  name: occu-webui
  version: 3.85.7
  epoch: 4
  description: "eQ-3 OCCU - HomeMatic WebUI"
  copyright:
    - license: HMSL
      license-path: occu-src/LicenseDE.txt
  dependencies:
    runtime:
      - lighttpd
      - occu
      - tclrega
      - tcl
  target-architecture:
    - aarch64
    - x86_64
  checks:
    disabled:
      - usrmerge
  scriptlets:
    post-install: |
      #!/bin/sh
      # Create required directories
      mkdir -p /etc/occu/config
      mkdir -p /www/rega

      # Copy templates to config if not exists
      if [ ! -f /etc/occu/config/rega.conf ]; then
        cp /etc/occu/config_templates/rega.conf /etc/occu/config/rega.conf
      fi
      if [ ! -f /etc/occu/config/InterfacesList.xml ]; then
        cp /etc/occu/config_templates/InterfacesList.xml /etc/occu/config/InterfacesList.xml
      fi
      if [ ! -f /etc/occu/config/time.conf ]; then
        cp /etc/occu/config_templates/time.conf /etc/occu/config/time.conf
      fi
      # Create empty regadom file if not exists (ReGaHss will populate it)
      if [ ! -f /etc/occu/config/homematic.regadom ]; then
        touch /etc/occu/config/homematic.regadom
      fi

      echo ""
      echo "=== OCCU WebUI installed ==="
      echo ""
      echo "To start ReGaHss:"
      echo "  rc-service occu-regahss start"
      echo "  rc-update add occu-regahss default"
      echo ""
      echo "Ports:"
      echo "  8183  ReGaHss HTTP (internal)"
      echo "  31999 ReGaHss XML-RPC"
      echo ""
      echo "Config files:"
      echo "  /etc/occu/rega.conf"
      echo "  /etc/occu/config/InterfacesList.xml"
      echo ""

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - ca-certificates
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/OpenCCU/occu.git
      tag: 3.85.7-2
      destination: occu-src

  - runs: |
      DESTDIR="${{targets.destdir}}"

      # Create directories
      mkdir -p "$DESTDIR/www"
      mkdir -p "$DESTDIR/etc/lighttpd"
      mkdir -p "$DESTDIR/etc/occu/config_templates"

      # Copy WebUI files - dereference symlinks to avoid broken /opt/hm references
      if [ -d "occu-src/WebUI/www" ]; then
        echo "Copying WebUI files..."
        # First copy with -L to dereference symlinks
        cp -rL occu-src/WebUI/www/* "$DESTDIR/www/" 2>/dev/null || true
        # Remove any remaining broken symlinks
        find "$DESTDIR/www" -xtype l -delete 2>/dev/null || true
      else
        echo "WARNING: occu-src/WebUI/www not found"
      fi

      # Copy Tcl scripts
      if [ -d "occu-src/WebUI/bin" ]; then
        mkdir -p "$DESTDIR/usr/local/bin"
        cp -r occu-src/WebUI/bin/* "$DESTDIR/usr/local/bin/" || true
      fi

      # Copy rega.conf template
      if [ -f "occu-src/WebUI/etc/rega.conf" ]; then
        install -Dm644 occu-src/WebUI/etc/rega.conf "$DESTDIR/etc/occu/rega.conf"
        install -Dm644 occu-src/WebUI/etc/rega.conf "$DESTDIR/etc/occu/config_templates/rega.conf"
      fi

      # Set permissions for CGI files
      find "$DESTDIR/www" -name "*.cgi" -exec chmod 755 {} \; 2>/dev/null || true
      find "$DESTDIR/www" -name "*.ccc" -exec chmod 755 {} \; 2>/dev/null || true

      # Install lighttpd configuration for OCCU
      mkdir -p "$DESTDIR/etc/lighttpd"
      cat > "$DESTDIR/etc/lighttpd/occu.conf" << 'EOF'
      # OCCU WebUI lighttpd configuration
      # Include this from /etc/lighttpd/lighttpd.conf

      server.modules += (
        "mod_cgi",
        "mod_alias",
        "mod_setenv"
      )

      # WebUI root
      alias.url += ( "/" => "/www/" )

      # CGI configuration for Tcl scripts
      cgi.assign = (
        ".cgi" => "/usr/bin/tclsh",
        ".ccc" => "/usr/bin/tclsh",
        ".tcl" => "/usr/bin/tclsh"
      )

      # Environment for CGI
      setenv.add-environment = (
        "DOCUMENT_ROOT" => "/www",
        "QUERY_STRING_UNESCAPED" => "true"
      )

      # MIME types
      mimetype.assign += (
        ".tcl" => "text/plain"
      )
      EOF

      # Ensure addons directory exists (symlink target created at runtime)
      mkdir -p "$DESTDIR/www/addons" || true

  # Install configuration templates
  - runs: |
      DESTDIR="${{targets.destdir}}"

      # Install rega.conf template
      install -Dm644 occu-webui/rega.conf "$DESTDIR/etc/occu/rega.conf"
      install -Dm644 occu-webui/rega.conf "$DESTDIR/etc/occu/config_templates/rega.conf"

      # Install InterfacesList.xml template
      install -Dm644 occu-webui/InterfacesList.xml "$DESTDIR/etc/occu/config_templates/InterfacesList.xml"

      # Install time.conf template
      install -Dm644 occu-webui/time.conf "$DESTDIR/etc/occu/config_templates/time.conf"

      # Create www/rega directory for ReGaHss HTTP document root
      mkdir -p "$DESTDIR/www/rega"

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
  pipeline:
    - runs: |
        # Test that WebUI files exist
        test -d /www
        test -f /etc/lighttpd/occu.conf

        # Test that config templates exist
        test -f /etc/occu/rega.conf
        test -f /etc/occu/config_templates/rega.conf
        test -f /etc/occu/config_templates/InterfacesList.xml
        test -f /etc/occu/config_templates/time.conf

        # Test that www/rega directory exists
        test -d /www/rega

        # Test no broken symlinks in /www
        ! find /www -xtype l | grep -q .
