package:
  name: occu-java
  version: 3.85.7
  epoch: 4
  description: "eQ-3 OCCU - HomeMatic IP Server (Java)"
  copyright:
    - license: HMSL
      license-path: occu-src/LicenseDE.txt
  dependencies:
    runtime:
      - java-jre-headless
      - occu
      - gcompat-custom
  target-architecture:
    - aarch64
    - x86_64
  checks:
    disabled:
      - usrmerge
  scriptlets:
    post-install: |
      #!/bin/sh
      echo ""
      echo "HMIPServer installed. Start with: rc-service occu-hmserver start"
      echo ""

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - ca-certificates
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/OpenCCU/occu.git
      tag: 3.85.7-2
      destination: occu-src

  - runs: |
      cd occu-src

      DESTDIR="${{targets.destdir}}"

      # Create directories
      mkdir -p "$DESTDIR/opt/HMServer"
      mkdir -p "$DESTDIR/opt/HmIP"
      mkdir -p "$DESTDIR/etc/occu/config_templates"

      # Install HMServer files
      if [ -d "HMserver/opt/HMServer" ]; then
        cp -r HMserver/opt/HMServer/* "$DESTDIR/opt/HMServer/"
      fi

      # Install HMServer Beta JARs (newer versions)
      if [ -d "HMServer-Beta/opt/HMServer" ]; then
        cp HMServer-Beta/opt/HMServer/*.jar "$DESTDIR/opt/HMServer/" 2>/dev/null || true
      fi

      # Install HmIP files
      if [ -d "HMserver/opt/HmIP" ]; then
        cp -r HMserver/opt/HmIP/* "$DESTDIR/opt/HmIP/"
      fi

      # Install hmip-copro-update.jar from Beta
      if [ -f "HMServer-Beta/opt/HmIP/hmip-copro-update.jar" ]; then
        cp HMServer-Beta/opt/HmIP/hmip-copro-update.jar "$DESTDIR/opt/HmIP/"
      fi

      # Install log4j2 config template
      if [ -f "HMserver/etc/config_templates/log4j2.xml" ]; then
        install -Dm644 HMserver/etc/config_templates/log4j2.xml "$DESTDIR/etc/occu/config_templates/log4j2.xml"
      fi

      # Install HMServer config template
      if [ -f "HMserver/etc/config_templates/HMServer.conf" ]; then
        install -Dm644 HMserver/etc/config_templates/HMServer.conf "$DESTDIR/etc/occu/config_templates/HMServer.conf"
      fi

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
  pipeline:
    - runs: |
        # Test that JAR files exist
        test -f /opt/HMServer/HMIPServer.jar || test -f /opt/HMServer/HMServer.jar
        test -f /etc/occu/config_templates/log4j2.xml
