package:
  name: tclrega
  version: 1.4
  epoch: 4
  description: "Tcl extension for ReGaHss communication"
  copyright:
    - license: LGPL-2.1-only
  dependencies:
    runtime:
      - tcl
  target-architecture:
    - aarch64
    - x86_64

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - build-base
      - tcl-dev

pipeline:
  - runs: |
      # Sources are bundled in tclrega/ directory (from OpenCCU project)
      cd tclrega

      # Build xmlParser object (statically linked into tclrega)
      # -fpermissive needed for legacy code (casts NULL to char)
      g++ -c -fPIC -O2 -pipe -fpermissive -Wno-class-memaccess xmlParser.cpp -o xmlParser.o

      # Build tclrega object
      g++ -c -fPIC -O2 -pipe -I. -I/usr/include/tcl8.6 tclrega.cpp -o tclrega.o

      # Link tclrega.so with xmlParser statically included
      g++ -shared -fPIC -o tclrega.so tclrega.o xmlParser.o -ltcl8.6

      # Install to /usr/lib per usrmerge standard
      install -Dm755 tclrega.so "${{targets.destdir}}/usr/lib/tclrega.so"

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
        - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      packages:
        - tcl
  pipeline:
    - runs: |
        # Test that tclrega.so exists and can be loaded
        test -f /usr/lib/tclrega.so
        # Try loading it in tclsh (will fail to connect but should load)
        echo "load /usr/lib/tclrega.so" | tclsh 2>&1 || true
