package:
  name: universal-silabs-flasher
  version: 0.1.3
  epoch: 1
  description: "Flash Silicon Labs radios running EmberZNet, CPC, or Gecko Bootloader firmware"
  copyright:
    - license: GPL-3.0-only
  options:
    no-depends: true
  dependencies:
    runtime:
      - python3
      - py3-aiohttp
      # click 8.2.0+ required (Alpine has 8.1.x) - bundled
      - py3-coloredlogs
      - py3-async-timeout
      - py3-typing-extensions
      - py3-cryptography
  target-architecture:
    - x86_64
    - aarch64
  checks:
    disabled:
      - usrmerge

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - ca-certificates
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      # System packages for dependencies (not bundled)
      - py3-aiohttp
      # py3-click excluded - need 8.2.0+, Alpine has 8.1.x
      - py3-coloredlogs
      - py3-async-timeout
      - py3-typing-extensions
      - py3-cryptography
  environment:
    PIP_CACHE_DIR: /var/cache/melange/pip

pipeline:
  - runs: |
      pyver=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
      sitepkgs="${{targets.destdir}}/usr/lib/python$pyver/site-packages"
      mkdir -p "$sitepkgs"

      # Only download packages not available in Alpine
      # zigpy, bellows, crc, gpiod, pyserial-asyncio-fast are not in Alpine repos
      # click 8.2.0+ required (Alpine has 8.1.x)
      python3 -m pip wheel \
        --wheel-dir .dist \
        "universal-silabs-flasher==${{package.version}}" \
        "click>=8.2.0" \
        "zigpy>=0.70.0" \
        "crc" \
        "bellows>=0.42.0" \
        "gpiod" \
        "pyserial-asyncio-fast"

      # Install wheels, skipping packages provided by Alpine
      for whl in .dist/*.whl; do
        case "$(basename "$whl")" in
          aiohttp-*|coloredlogs-*|async_timeout-*|typing_extensions-*|cryptography-*)
            echo "Skipping $whl (provided by Alpine)"
            continue
            ;;
          # Skip transitive dependencies also provided by Alpine
          attrs-*|yarl-*|multidict-*|frozenlist-*|charset_normalizer-*|cffi-*|pycparser-*|idna-*|aiohappyeyeballs-*|propcache-*|humanfriendly-*)
            echo "Skipping $whl (provided by Alpine)"
            continue
            ;;
        esac
        python3 -m pip install \
          --no-deps \
          --no-compile \
          --target "$sitepkgs" \
          "$whl"
      done

      # Byte-compile Python files
      python3 -m compileall -q "$sitepkgs" || true

      # Create bin directory and install entry point
      install -dm755 "${{targets.destdir}}"/usr/bin

      printf '%s\n' '#!/usr/bin/python3' 'import sys' 'from universal_silabs_flasher.__main__ import main' 'sys.exit(main())' > "${{targets.destdir}}"/usr/bin/universal-silabs-flasher
      chmod 755 "${{targets.destdir}}"/usr/bin/universal-silabs-flasher

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/edge/main
        - https://dl-cdn.alpinelinux.org/alpine/edge/community
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      packages:
        - busybox
  pipeline:
    - runs: |
        # Test that the module can be imported
        python3 -c "from universal_silabs_flasher.__main__ import main; print('module OK')"
    - runs: |
        # Test help output
        universal-silabs-flasher --help
