package:
  name: universal-silabs-flasher
  version: 0.1.3
  epoch: 0
  description: "Flash Silicon Labs radios running EmberZNet, CPC, or Gecko Bootloader firmware"
  copyright:
    - license: GPL-3.0-only
  options:
    no-depends: true
  dependencies:
    runtime:
      - python3
  target-architecture:
    - x86_64
    - aarch64
  checks:
    disabled:
      - usrmerge

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    keyring:
      - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
    packages:
      - busybox
      - ca-certificates
      - python3
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - git
  environment:
    PIP_CACHE_DIR: /var/cache/melange/pip

pipeline:
  - runs: |
      pyver=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
      sitepkgs="${{targets.destdir}}/usr/lib/python$pyver/site-packages"
      mkdir -p "$sitepkgs"

      # Download and build all wheels
      python3 -m pip wheel \
        --wheel-dir .dist \
        "universal-silabs-flasher==${{package.version}}" \
        "aiohttp" \
        "click>=8.2.0" \
        "zigpy>=0.70.0" \
        "crc" \
        "bellows>=0.42.0" \
        "gpiod" \
        "coloredlogs" \
        "async-timeout" \
        "typing_extensions" \
        "pyserial-asyncio-fast"

      # Install all wheels
      for whl in .dist/*.whl; do
        python3 -m pip install \
          --no-deps \
          --no-compile \
          --target "$sitepkgs" \
          "$whl"
      done

      # Byte-compile Python files
      python3 -m compileall -q "$sitepkgs" || true

      # Create bin directory and install entry point
      install -dm755 "${{targets.destdir}}"/usr/bin

      printf '%s\n' '#!/usr/bin/python3' 'import sys' 'from universal_silabs_flasher.__main__ import main' 'sys.exit(main())' > "${{targets.destdir}}"/usr/bin/universal-silabs-flasher
      chmod 755 "${{targets.destdir}}"/usr/bin/universal-silabs-flasher

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/edge/main
        - https://dl-cdn.alpinelinux.org/alpine/edge/community
      keyring:
        - https://alpinelinux.org/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      packages:
        - busybox
  pipeline:
    - runs: |
        # Test that the module can be imported
        python3 -c "from universal_silabs_flasher.__main__ import main; print('module OK')"
    - runs: |
        # Test help output
        universal-silabs-flasher --help
